prometheus/demo-site

README.md
extras.yml
files/index.html
hosts

Signed-off-by: Ben Kochie <bjk@gitlab.com>

Update site branding for Prometheus.

---

.circleci/config.yml

Persist build output to workspace.

Fix build artifact

---

playbooks/01_webserver.yml
playbooks/files/img/logo.png

Workaround for git lfs limitations in circleci

use remote links for site images

---

.circleci/config.yml

Re-add #12

---

playbooks/01_webserver.yml
playbooks/files/img/logo.png
playbooks/files/index.html

Just making this more visually pleasant. It still needs a lot of work.

rearrange cards on portal site

---

playbooks/02_monitoring.yml

- Ensuring exporters are started and enabled
- Fix restart handler

playbooks: ensure random_exporters are started and enabled

---

README.md

Updated the README file to manually download & copy it at the appropriate location as [suggested ](https://github.com/prometheus/demo-site/issues/32#issuecomment-641933285)on the issue #32 .

To fix the issue #32 with random_exporter binary.

---

.circleci/config.yml
playbooks/02_monitoring.yml
playbooks/files/index.html
requirements.txt
roles/requirements.yml

Use new Galaxy role name.
* Update Ansible version.
* Update Go version.
* Update prometheus default branch name.

Update node_exporter role.

---

group_vars/prometheus.yml

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

Enable experimental promql features

---

group_vars/prometheus.yml

Avoid jinja template expansion of Go template.
Signed-off-by: SuperQ <superq@gmail.com>

Use raw string for alert description

---

group_vars/prometheus.yml

Yessssssssssssssssss
Signed-off-by: SuperQ <superq@gmail.com>

Can has more raw

---

.circleci/config.yml
group_vars/exporters.yml
playbooks/templates/node_metrics.prom.j2

.circleci: add test-deploy job

---

.ansible-lint
.circleci/config.yml
.yamllint
group_vars/alertmanager.yml
group_vars/grafana/vars.yml
group_vars/prometheus.yml
playbooks/00_system.yml
playbooks/01_webserver.yml
playbooks/02_monitoring.yml

Add a Lint job in circleci, similar to what the Cloud Alchemy ansible roles are doing.

ansible-lint

---

.circleci/config.yml
group_vars/alertmanager.yml
group_vars/all.yml
molecule/default/converge.yml
molecule/default/prepare.yml
molecule/test-requirements.txt
playbooks/00_system.yml
playbooks/01_webserver.yml
playbooks/02_monitoring.yml
roles/requirements.yml
site.yml

Switching to use collections instead of deprecated roles.

WIP: use collection instead of deprecated roles

---

playbooks/02_monitoring.yml
playbooks/files/index.html
roles/requirements.yml

Switch Grafana to use the official Ansible collection/role.

Switch Grafana to official collection

---

playbooks/00_system.yml
playbooks/02_monitoring.yml

* Add cadvisor role to common node monitoring.
* Enable CPU accounting on systemd units for cdvisor role.

Add cAdvisor to monitor cgroups

---

group_vars/prometheus.yml

Scrape the cAdvisor endpoint
* Allow staleness timestamps.

Add scrape configuration for cAdvisor

---

group_vars/prometheus.yml

Fix config boolean rendering error.

Fix cadvisor config

---

group_vars/web/web.yml
playbooks/templates/Caddyfile.j2
site.yml

Re-enable websrever deploy now that the ansible role is working again.
* Enable updates.
* Move Caddyfile to template file.

Fixup webserver deployment

---

.circleci/config.yml
group_vars/prometheus.yml

https://github.com/prometheus-community/ansible/pull/333

fix: use yaml rule files

---

roles/requirements.yml

should be kept up to date by renovate from now on

fix: pin ansible collection and role versions

---

.circleci/config.yml
README.md
hosts
playbooks/01_webserver.yml
playbooks/02_monitoring.yml
playbooks/files/img/digitalocean.png
playbooks/files/index.html

Move the hosting to our new server.
* Remove DigitialOcean references now that we're on a new hosting platform.

Migrate to new hosting
