prometheus/demo-site

group_vars/exporters.yml, group_vars/prometheus.yml, group_vars/web.yml, hosts, playbooks/02_monitoring.yml
- remove snmp-exporter deployment
- blackbox-exporter should listen on localhost only
- remove snmp and blackbox exporters from caddy
Signed-off-by: paulfantom <pawel@krupa.net.pl>
=> remove snmp-exporter and secure blackbox exporter

.circleci/config.yml
I have no idea why it worked, but fingerprint was wrong.
=> .circleci: fix incorrect ssh fingerprint

playbooks/01_webserver.yml
=> Fix DO logo download

README.md, group_vars/prometheus.yml, playbooks/02_monitoring.yml
- Add better random_exporter systemd service file which allows specifying multiple random exporters (right now it set to 4) - fixes #3 
- minor fixes in readme
- fixed license badge
- removed links to blackbox and snmp exporters
Number of random_exporters is controlled by `random_exporter_addresses` list in `group_vars/prometheus.yml`
=> More random_exporters; fixes in readme

.circleci/config.yml
Without it deployments after merging anything to `master` may fail.
=> .circleci: make mixins stage required for deployment

.circleci/config.yml
This should generate and copy dashboards from prometheus and node_exporter mixins. Currently, due to bug in ansible-grafana role, dashboards cannot be uploaded.
Blocked by: https://github.com/cloudalchemy/ansible-grafana/pull/197
=> create grafana dashboards from mixins

group_vars/prometheus.yml
I have also created
https://github.com/cloudalchemy/ansible-prometheus/pull/267
But I think we can keep the version explicit here, it will quickly
enable us to update to release candidates, instead of playing the game
of adding/removing lines each time.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Update prometheus to 2.16.0

group_vars/web.yml
Caddy v1 website changed API and current download link doesn't work.
This is a temporary stop-gap solution until https://github.com/caddy-ansible/caddy-ansible/pull/6 is merged and we can migrate to v2
/cc @SuperQ
=> disable caddy updates

group_vars/web/web.yml
Remove the obsolete `prometheus` config from Caddy. It now automatically
listens on the default admin localhost:2019.
=> Remove obsolete `prometheus` config

group_vars/web/web.yml
Fix demo site homepage content by enabling the file_server directive.
=> Enable missing file_server in Caddy

group_vars/web/web.yml
Recently demo-site deploys stopped working due to an issue with caddy updates (reported in https://github.com/caddy-ansible/caddy-ansible/issues/13). With this PR deploys should start working again.
=> group_vars: disable caddy updates

site.yml
Seems like the ansible role managing caddy is broken. For now, let's disable it to allow clean updates for monitoring stack.
=> Temporarily disable caddy updates

group_vars/exporters.yml, group_vars/prometheus.yml, playbooks/02_monitoring.yml, playbooks/templates/node_metrics.prom.j2
Add an example of how to use a node_exporter textfile metric as a
threshold for alerting.
Signed-off-by: SuperQ <superq@gmail.com>
=> Add a node metric threshold example

.circleci/config.yml, group_vars/prometheus.yml, molecule/default/converge.yml, molecule/default/host_vars/bionic.yml, molecule/default/molecule.yml, molecule/default/prepare.yml, molecule/test-requirements.txt, playbooks/00_system.yml
CircleCI builds on pull requests have been failing.  It looks like one reason is because they are trying to run ansible on the production server.  It would be safer to test pull requests in an isolated docker container instead, using molecule tests.
A discovery is that although 'ansible_host' appears to be one of those magical automatic ansible variables, it isn't.   
If you want to use 'ansible_host' in the inventory you have to set it manually.  Many real-world ansible deployments might not have 'ansible_host' configured.   As an alternative, why not allow the playbooks to use 'inventory_hostname'.  So, that has been added here.
=> fixing circleci builds

playbooks/files/index.html
The link was `404`ing because of the `master` to `main` switch, and also GitHub seems to be redirecting to the `raw.githubusercontent.com` subdomain so might as well use it here.
=> Fix Prometheus logo link

README.md
The "last build" link incorrectly points to Travis CI which we no longer use.
=> Change Travis CI link to CircleCI

playbooks/files/index.html
Hi @LeviHarrison, on a related note, the logo link fix #67 is not reflected in current deployment of the demo website at https://demo.do.prometheus.io/, would you be able to trigger a new build?
=> Fix favicon link

group_vars/grafana/vars.yml
The Grafana role disables metrics unless the `grafana_metrics` is a non-empty dict.
=> Re-enable Grafana metrics

group_vars/grafana/vars.yml, roles/requirements.yml
Grafana legacy alerting has been removed from Grafana 11.0.
* Bump Grafana collection.
=> Disable Grafana alerting

group_vars/grafana/vars.yml
An earlier version of demo-site included the variable `grafana_dashboards: []` which I thought was a nice reminder of what the variable name is and that it should probably be configured.    We are using `grafana_dashboards`.  
If you do set that variable now, the grafana role complains `grafana_datasources` is missing.   
Based on that discovery, it seems the renaming of `grafana_datasources` to `datasources` in this vars.yml file didn't match the upstream grafana role and so maybe "datasources" is being ignored.  
This PR partially reverts the file `group_vars/grafana/vars.yml` to a previous state.    Things are working better. but if you believe I am missing other details about the topic and this is incorrect, let me know.
=> grafana_dashboards variable
